First cut of adding multiple OS builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,13 @@
 language: ruby
 
-os: linux
+os:
+  - linux
+  - osx
+  - windows
+jobs:
+  allow_failures:
+    - osx
+    - windows
 sudo: required
 dist: trusty
 addons:
@@ -38,27 +45,65 @@ rvm:
   - 2.4.4
   - 2.5.1
 
-before_install:
- - wget http://aubio.org/pub/aubio-0.4.4.tar.bz2
- - tar xvjf aubio-0.4.4.tar.bz2
- - cd aubio-0.4.4
- - ./waf configure build
- - sudo ./waf install
-
-script:
- - set -e
+install:
 # the | starts a multiline YAML entry
  - |
-    # this compiles the gems and runs the Sonic Pi test suite with the ruby installed through Travis's rvm
+    #!/usr/bin/env bash
+    set -euo pipefail
+    case "$TRAVIS_OS_NAME" in
+    linux)
+        wget http://aubio.org/pub/aubio-0.4.4.tar.bz2
+        tar xvjf aubio-0.4.4.tar.bz2
+        cd aubio-0.4.4
+        ./waf configure build
+        sudo ./waf install
+        ;;
+    osx)
+        echo "OSX, yeah!"
+        ;;
+    windows)
+        echo "Windows, oooh!"
+        ;;
+    *)
+        echo "ERROR: Unsupported OS $TRAVIS_OS_NAME"
+        exit 1
+    esac
+    # this compiles the gems and runs the Sonic Pi test suite 
+    # with the ruby installed through Travis's rvm
     echo ""
     echo "***********************************"
     echo "* Compiling the vendor/ ruby gems *"
     echo "***********************************"
-    cd $TRAVIS_BUILD_DIR/app/server/ruby/bin
+    cd "$TRAVIS_BUILD_DIR/app/server/ruby/bin"
     ruby ./compile-extensions.rb
+
+script:
+ - |
+    #!/usr/bin/env bash
+    set -euo pipefail
     echo ""
     echo "***********************************"
     echo "* Running the Sonic Pi test suite *"
     echo "***********************************"
-    cd $TRAVIS_BUILD_DIR/app/server/ruby/test
+    cd "$TRAVIS_BUILD_DIR/app/server/ruby/test"
     rake test
+
+deploy:
+ - |
+    #!/usr/bin/env bash
+    set -euo pipefail
+    case "$TRAVIS_OS_NAME" in
+    linux)
+        app/gui/qt/build-ubuntu-app
+        ;;
+    osx)
+        app/gui/qt/build-osx-app
+        ;;
+    windows)
+        cd app/gui/qt
+        powershell build-windows-app.ps1
+        ;;
+    *)
+        echo "ERROR: Unsupported OS $TRAVIS_OS_NAME"
+        exit 1
+    esac
